// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7H_QAWTgPxaskFSz0STgy3O05jv9TkAM',
    appId: '1:133702448034:web:09cf41c353e5396f0938fb',
    messagingSenderId: '133702448034',
    projectId: 'chat-app-d73a2',
    authDomain: 'chat-app-d73a2.firebaseapp.com',
    storageBucket: 'chat-app-d73a2.firebasestorage.app',
    measurementId: 'G-R6EPZGVPSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJz8vMCSlOpp_ca0x2yGz1joZSJ_v_Ps',
    appId: '1:133702448034:android:8ee9970b3dce57ff0938fb',
    messagingSenderId: '133702448034',
    projectId: 'chat-app-d73a2',
    storageBucket: 'chat-app-d73a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzXCzjgBT1rMHNin-zWN2ZLBL60Qfcj1M',
    appId: '1:133702448034:ios:d1cae1f1b889cc220938fb',
    messagingSenderId: '133702448034',
    projectId: 'chat-app-d73a2',
    storageBucket: 'chat-app-d73a2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzXCzjgBT1rMHNin-zWN2ZLBL60Qfcj1M',
    appId: '1:133702448034:ios:d1cae1f1b889cc220938fb',
    messagingSenderId: '133702448034',
    projectId: 'chat-app-d73a2',
    storageBucket: 'chat-app-d73a2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7H_QAWTgPxaskFSz0STgy3O05jv9TkAM',
    appId: '1:133702448034:web:c20b06f760e7c1bd0938fb',
    messagingSenderId: '133702448034',
    projectId: 'chat-app-d73a2',
    authDomain: 'chat-app-d73a2.firebaseapp.com',
    storageBucket: 'chat-app-d73a2.firebasestorage.app',
    measurementId: 'G-PVHG323MLL',
  );
}
